import Providers from "@/lib/query-provider";
import { CookiesProvider } from "next-client-cookies/server";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Archimatch",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <CookiesProvider>
          <Providers>
            {children}

            <ToastContainer
              limit={1}
              newestOnTop={true}
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              closeOnClick={true}
              pauseOnHover={true}
              draggable={true}
              progress={undefined}
            />
          </Providers>
        </CookiesProvider>
      </body>
    </html>
  );
};
export default RootLayout;
