"use client";
 

import {
    BarsArrowUpIcon,
    CalendarIcon,
    CheckIcon,
    ChevronDownIcon,
    ClipboardDocumentListIcon,
    Cog6ToothIcon,
    Cog8ToothIcon,
    CreditCardIcon,
    CurrencyDollarIcon,
    DocumentCheckIcon,
    ExclamationCircleIcon,
    ExclamationTriangleIcon,
    EyeIcon,
    GiftIcon,
    InboxIcon,
    LifebuoyIcon,
    MegaphoneIcon,
    PencilIcon,
    PlusIcon,
    PowerIcon,
    PresentationChartBarIcon,
    TableCellsIcon,
    TicketIcon,
    TrashIcon,
    UserCircleIcon,
    UserGroupIcon,
    UserPlusIcon,
    XMarkIcon,
} from "@heroicons/react/24/solid";
import {
    Avatar,
    Button,
    CardBody,
    CardFooter,
    CardHeader,
    Checkbox,
    Chip,
    Dialog,
    DialogBody,
    DialogFooter,
    DialogHeader,
    Drawer, IconButton, Input, List,
    ListItem,
    ListItemPrefix,
    ListItemSuffix,
    Menu,
    MenuHandler,
    MenuItem,
    MenuList,
    MobileNav, Navbar,
    Option,
    Popover,
    PopoverContent,
    PopoverHandler,
    Progress,
    Radio,
    Rating,
    Select,
    Step,
    Stepper,
    Switch,
    Tab,
    TabPanel,
    Tabs,
    TabsBody,
    TabsHeader,
    ThemeProvider, Typography, focus, otp_area,
} from "@material-tailwind/react";
 
export {
    Avatar, BarsArrowUpIcon, Button, CalendarIcon, CardBody,
    CardFooter,
    CardHeader, CheckIcon, Checkbox, ChevronDownIcon, Chip, ClipboardDocumentListIcon,
    Cog6ToothIcon,
    Cog8ToothIcon, CreditCardIcon,
    CurrencyDollarIcon, Dialog,
    DialogBody,
    DialogFooter,
    DialogHeader, DocumentCheckIcon, Drawer, ExclamationCircleIcon, ExclamationTriangleIcon,
    EyeIcon,
    GiftIcon, IconButton, InboxIcon, Input, LifebuoyIcon, List,
    ListItem,
    ListItemPrefix,
    ListItemSuffix, MegaphoneIcon, Menu,
    MenuHandler,
    MenuItem,
    MenuList,
    MobileNav, Navbar,
    Option, PencilIcon,
    PlusIcon, Popover,
    PopoverContent,
    PopoverHandler, PowerIcon,
    PresentationChartBarIcon, Progress, Radio, Rating,
    Select,
    Step,
    Stepper, Switch, Tab, TabPanel, TableCellsIcon, Tabs, TabsBody, TabsHeader,
    ThemeProvider, TicketIcon,
    TrashIcon, Typography, UserCircleIcon,
    UserGroupIcon,
    UserPlusIcon,
    XMarkIcon, focus, otp_area
};

